package com.charactor.avatar.maker.pfp.activity_app.nickname

import com.charactor.avatar.maker.pfp.core.utils.UnicodeStyleConverter

object CustomizeNicknameActivityStyleApplier {

    fun applyUnicodeStyle(text: String, styleType: StyleType): String {
        val conv = UnicodeStyleConverter
        return when (styleType) {
            // Mathematical Alphanumeric (13)
            StyleType.BOLD -> conv.toBold(text)
            StyleType.ITALIC -> conv.toItalic(text)
            StyleType.BOLD_ITALIC -> conv.toBoldItalic(text)
            StyleType.SCRIPT -> conv.toScript(text)
            StyleType.BOLD_SCRIPT -> conv.toBoldScript(text)
            StyleType.FRAKTUR -> conv.toFraktur(text)
            StyleType.BOLD_FRAKTUR -> conv.toBoldFraktur(text)
            StyleType.DOUBLE_STRUCK -> conv.toDoubleStruck(text)
            StyleType.SANS -> conv.toSans(text)
            StyleType.SANS_BOLD -> conv.toSansBold(text)
            StyleType.SANS_ITALIC -> conv.toSansItalic(text)
            StyleType.SANS_BOLD_ITALIC -> conv.toSansBoldItalic(text)
            StyleType.MONOSPACE -> conv.toMonospace(text)

            // Enclosed Characters (5)
            StyleType.CIRCLED -> conv.toCircled(text)
            StyleType.SQUARED -> conv.toSquared(text)
            StyleType.NEGATIVE_CIRCLED -> conv.toNegativeCircled(text)
            StyleType.NEGATIVE_SQUARED -> conv.toNegativeSquared(text)
            StyleType.PARENTHESIZED -> conv.toParenthesized(text)

            // Special Unicode Blocks (6)
            StyleType.FULLWIDTH -> conv.toFullwidth(text)
            StyleType.SMALL_CAPS -> conv.toSmallCaps(text)
            StyleType.SUPERSCRIPT -> conv.toSuperscript(text)
            StyleType.SUBSCRIPT -> conv.toSubscript(text)
            StyleType.INVERTED -> conv.toInverted(text)
            StyleType.REGIONAL_INDICATOR -> conv.toRegionalIndicator(text)

            // Basic Combining Characters (8)
            StyleType.STRIKETHROUGH -> conv.toStrikethrough(text)
            StyleType.UNDERLINE -> conv.toUnderline(text)
            StyleType.OVERLINE -> conv.toOverline(text)
            StyleType.SLASH -> conv.toSlash(text)
            StyleType.DOTTED -> conv.toDotted(text)
            StyleType.DOUBLE_UNDERLINE -> conv.toDoubleUnderline(text)
            StyleType.TILDE -> conv.toTilde(text)
            StyleType.RING_ABOVE -> conv.toRingAbove(text)

            // More Combining Diacritics (8)
            StyleType.DIAERESIS -> conv.toDiaeresis(text)
            StyleType.ACUTE -> conv.toAcute(text)
            StyleType.GRAVE -> conv.toGrave(text)
            StyleType.CIRCUMFLEX -> conv.toCircumflex(text)
            StyleType.CARON -> conv.toCaron(text)
            StyleType.BREVE -> conv.toBreve(text)
            StyleType.MACRON -> conv.toMacron(text)
            StyleType.DOUBLE_ACUTE -> conv.toDoubleAcute(text)

            // Mathematical Style + Underline (5)
            StyleType.SCRIPT_UNDERLINE -> conv.toScriptUnderline(text)
            StyleType.FRAKTUR_UNDERLINE -> conv.toFrakturUnderline(text)
            StyleType.MONOSPACE_UNDERLINE -> conv.toMonospaceUnderline(text)
            StyleType.SANS_BOLD_UNDERLINE -> conv.toSansBoldUnderline(text)
            StyleType.DOUBLE_STRUCK_UNDERLINE -> conv.toDoubleStruckUnderline(text)

            // Bold/Italic Combinations (6)
            StyleType.BOLD_UNDERLINE -> conv.toBoldUnderline(text)
            StyleType.ITALIC_UNDERLINE -> conv.toItalicUnderline(text)
            StyleType.BOLD_STRIKETHROUGH -> conv.toBoldStrikethrough(text)
            StyleType.BOLD_DOTTED -> conv.toBoldDotted(text)
            StyleType.ITALIC_DOTTED -> conv.toItalicDotted(text)
            StyleType.BOLD_TILDE -> conv.toBoldTilde(text)

            // Italic/Other Combinations (1)
            StyleType.ITALIC_STRIKETHROUGH -> conv.toItalicStrikethrough(text)

            // More Mathematical + Combining (7)
            StyleType.BOLD_CIRCUMFLEX -> conv.toBoldCircumflex(text)
            StyleType.ITALIC_CARON -> conv.toItalicCaron(text)
            StyleType.SCRIPT_TILDE -> conv.toScriptTilde(text)
            StyleType.MONOSPACE_STRIKETHROUGH -> conv.toMonospaceStrikethrough(text)
            StyleType.SANS_BOLD_STRIKETHROUGH -> conv.toSansBoldStrikethrough(text)
            StyleType.FRAKTUR_DOTTED -> conv.toFrakturDotted(text)
            StyleType.DOUBLE_STRUCK_STRIKETHROUGH -> conv.toDoubleStruckStrikethrough(text)

            // Zalgo/Glitch (3)
            StyleType.ZALGO_LIGHT -> conv.toZalgoLight(text)
            StyleType.ZALGO_MEDIUM -> conv.toZalgoMedium(text)
            StyleType.ZALGO_HEAVY -> conv.toZalgoHeavy(text)

            // Decorative Brackets (15)
            StyleType.SQUARE_BRACKETS -> conv.toSquareBrackets(text)
            StyleType.DOUBLE_BRACKETS -> conv.toDoubleBrackets(text)
            StyleType.CURLY_BRACKETS -> conv.toCurlyBrackets(text)
            StyleType.WHITE_BRACKETS -> conv.toWhiteBrackets(text)
            StyleType.TORTOISE_BRACKETS -> conv.toTortoiseBrackets(text)
            StyleType.ANGLE_BRACKETS -> conv.toAngleBrackets(text)
            StyleType.DOUBLE_ANGLE_BRACKETS -> conv.toDoubleAngleBrackets(text)
            StyleType.CORNER_BRACKETS -> conv.toCornerBrackets(text)
            StyleType.FLOOR_BRACKETS -> conv.toFloorBrackets(text)
            StyleType.PARENTHESES -> conv.toParentheses(text)
            StyleType.SQUARE_PARENTHESES -> conv.toSquareParentheses(text)
            StyleType.CURLY_PARENTHESES -> conv.toCurlyParentheses(text)
            StyleType.ARROW_BRACKETS -> conv.toArrowBrackets(text)
            StyleType.QUOTATION_MARKS -> conv.toQuotationMarks(text)
            StyleType.SINGLE_QUOTES -> conv.toSingleQuotes(text)

            // Emoji Decorations (5)
            StyleType.STARS -> conv.toStars(text)
            StyleType.HEARTS -> conv.toHearts(text)
            StyleType.SPARKLES -> conv.toSparkles(text)
            StyleType.CROWN -> conv.toCrown(text)
            StyleType.FLOWERS -> conv.toFlowers(text)

            // Arrow Decorations (5)
            StyleType.ARROWS_LEFT -> conv.toArrowsLeft(text)
            StyleType.ARROWS_RIGHT -> conv.toArrowsRight(text)
            StyleType.ARROWS_BOTH -> conv.toArrowsBoth(text)
            StyleType.DOUBLE_ARROWS -> conv.toDoubleArrows(text)
            StyleType.TRIANGLE_ARROWS -> conv.toTriangleArrows(text)

            // Box Drawing (4)
            StyleType.BOX_SINGLE -> conv.toBoxSingle(text)
            StyleType.BOX_DOUBLE -> conv.toBoxDouble(text)
            StyleType.BOX_ROUNDED -> conv.toBoxRounded(text)
            StyleType.BOX_HEAVY -> conv.toBoxHeavy(text)

            // Block Backgrounds (4)
            StyleType.BLOCK_LIGHT -> conv.toBlockLight(text)
            StyleType.BLOCK_MEDIUM -> conv.toBlockMedium(text)
            StyleType.BLOCK_HEAVY -> conv.toBlockHeavy(text)
            StyleType.BLOCK_FULL -> conv.toBlockFull(text)

            // Character Substitution / Lookalike (7)
            StyleType.CYRILLIC_LOOKALIKE -> conv.toCyrillicLookalike(text)
            StyleType.GREEK_LOOKALIKE -> conv.toGreekLookalike(text)
            StyleType.ASIAN_MIX -> conv.toAsianMix(text)
            StyleType.MATH_SYMBOLS -> conv.toMathSymbols(text)
            StyleType.WEIRD_MIX -> conv.toWeirdMix(text)
            StyleType.SQUARED_NEGATIVE_LOOKALIKE -> conv.toSquaredNegativeLookalike(text)
            StyleType.CURRENCY_MIX -> conv.toCurrencyMix(text)

            // Mixed / Random Styles (13)
            StyleType.MIXED_LIGHT -> conv.toMixedLight(text)
            StyleType.MIXED_MEDIUM -> conv.toMixedMedium(text)
            StyleType.MIXED_HEAVY -> conv.toMixedHeavy(text)
            StyleType.ALTERNATING_CASE -> conv.toAlternatingCase(text)
            StyleType.RANDOM_CASE -> conv.toRandomCase(text)
            StyleType.MIXED_SUBSTITUTION -> conv.toMixedSubstitution(text)
            StyleType.ALTERNATING_STYLES -> conv.toAlternatingStyles(text)
            StyleType.WAVE_STYLE -> conv.toWaveStyle(text)
            StyleType.BUBBLE_TEXT -> conv.toBubbleText(text)
            StyleType.FANCY_MIX -> conv.toFancyMix(text)
            StyleType.AESTHETIC -> conv.toAesthetic(text)
            StyleType.VAPORWAVE -> conv.toVaporwave(text)
            StyleType.GLITCH_MIX -> conv.toGlitchMix(text)
            StyleType.CRAZY_MIX -> conv.toCrazyMix(text)

            // Mixed Script Styles (15)
            StyleType.ARMENIAN -> conv.toArmenian(text)
            StyleType.THAI_LAO_MIX -> conv.toThaiLaoMix(text)
            StyleType.JAPANESE_MIX -> conv.toJapaneseMix(text)
            StyleType.MEDIEVAL_LATIN -> conv.toMedievalLatin(text)
            StyleType.BOPOMOFO_CJK -> conv.toBopomofoCJK(text)
            StyleType.YI_SYLLABLES -> conv.toYiSyllables(text)
            StyleType.CANADIAN_ABORIGINAL -> conv.toCanadianAboriginal(text)
            StyleType.CHEROKEE -> conv.toCherokee(text)
            StyleType.LISU -> conv.toLisu(text)
            StyleType.HEBREW_GREEK_MIX -> conv.toHebrewGreekMix(text)
            StyleType.GUJARATI_MIX -> conv.toGujaratiMix(text)
            StyleType.THAI_ARMENIAN_MIX -> conv.toThaiArmenianMix(text)
            StyleType.CYRILLIC_ARMENIAN_MIX -> conv.toCyrillicArmenianMix(text)
            StyleType.GREEK_CYRILLIC_MIX -> conv.toGreekCyrillicMix(text)
            StyleType.LATIN_GREEK_VIETNAMESE_MIX -> conv.toLatinGreekVietnameseMix(text)

            // IPA & Phonetic Styles (3)
            StyleType.IPA_PHONETIC -> conv.toIPAPhonetic(text)
            StyleType.IPA_EXTENDED -> conv.toIPAExtended(text)
            StyleType.PHONETIC_EXTENSIONS -> conv.toPhoneticExtensions(text)

            // Advanced Greek Variants (3)
            StyleType.GREEK_EXTENDED -> conv.toGreekExtended(text)
            StyleType.GREEK_COPTIC_MIX -> conv.toGreekCopticMix(text)
            StyleType.GREEK_ARCHAIC -> conv.toGreekArchaic(text)

            // Symbol Separators (6)
            StyleType.SEPARATOR_N_ARY -> conv.toSeparatorNAry(text)
            StyleType.SEPARATOR_APL -> conv.toSeparatorAPL(text)
            StyleType.SEPARATOR_STAR -> conv.toSeparatorStar(text)
            StyleType.SEPARATOR_DOT -> conv.toSeparatorDot(text)
            StyleType.SEPARATOR_DIAMOND -> conv.toSeparatorDiamond(text)
            StyleType.SEPARATOR_CIRCLE -> conv.toSeparatorCircle(text)

            // Complex Combining Marks (8)
            StyleType.COMBINING_INVERTED_BRIDGE -> conv.toCombiningInvertedBridge(text)
            StyleType.COMBINING_CANDRABINDU -> conv.toCombiningCandrabindu(text)
            StyleType.COMBINING_ZIGZAG -> conv.toCombiningZigzag(text)
            StyleType.COMBINING_ARROW -> conv.toCombiningArrow(text)
            StyleType.DOUBLE_STRUCK_MULTI_DIACRITICS -> conv.toDoubleStruckMultiDiacritics(text)
            StyleType.DIACRITICS_RANDOM_HEAVY -> conv.toDiacriticsRandomHeavy(text)
            StyleType.SUPERSCRIPT_DIACRITICS_MIX -> conv.toSuperscriptDiacriticsMix(text)
            StyleType.SUBSCRIPT_DIACRITICS_MIX -> conv.toSubscriptDiacriticsMix(text)

            // Mirrored & Flipped Styles (2)
            StyleType.MIRRORED_REVERSED -> conv.toMirroredReversed(text)
            StyleType.UPSIDE_DOWN_MIRRORED -> conv.toUpsideDownMirrored(text)

            // Heavy Effects (4)
            StyleType.ZALGO_ARROWS -> conv.toZalgoArrows(text)
            StyleType.GLITCH_HEAVY_MARKS -> conv.toGlitchHeavyMarks(text)
            StyleType.CHAOTIC_MIX -> conv.toChaoticMix(text)
            StyleType.EXTREME_COMBINING -> conv.toExtremeCombining(text)
        }
    }
}
